### ISSUE TITLE
Undefined property: stdClass::$content when clicking "Subscribe" button

### ISSUE THREAD

**Issue by 01010000101001100** [getgrav/grav-plugin-feed#10]
Getting:
```
Whoops \ Exception \ ErrorException (E_NOTICE)
Undefined property: stdClass::$content
```
at `/­feed/­feed.php:86` line.

Also I noticed the error page took me to `mywebsite.xyz/.rss` (notice the dot) and `/rss` its 404 page - is that how supposed to be?

**Comment by flaviocopes** [comment]
Most probably the page you are on is not defining a collection in its header. E.g. it's not a blog posts list. Is this the case?

**Comment by 01010000101001100** [comment]
@flaviocopes it was a page template if I am not mistaken. Can we make this button works at any type of pages?

**Comment by flaviocopes** [comment]
This is probably meant to work on collection pages.

The "Subscribe" button is created by your theme. If you search for it, you can change its link to be fixed to your blog posts RSS, instead of trying to determine it based on the page it's shown in.
