### ISSUE TITLE
Filter feed on taxonomy

### ISSUE THREAD

**Issue by rsmarples** [getgrav/grav-plugin-feed#12]
I'd like to filter the feed by taxonomy if possible. For example, I would only want to allow blog posts tagged FaceBook to appear in the FaceBook feed I've setup.

Ideally this should be driven by the url - blog.rss?tag=facebook

**Comment by phideas** [comment]
It would be awesome to have this feature in feed!

**Comment by flaviocopes** [comment]
Use Grav. Create a hidden `blog.md` page, which lists the posts tagged "facebook" descendants of the main blog. Then call this hidden page with .rss

**Comment by rsmarples** [comment]
That's an awesome idea! Maybe add it to some documentation?

**Comment by phideas** [comment]
Thanks for quick tip! :)

**Comment by flaviocopes** [comment]
@rsmarples feel free to add a line about this in https://github.com/getgrav/grav-plugin-feed/blob/develop/README.md, you can edit it directly on GitHub.
