### ISSUE TITLE
Feed plugin is always summarised even when summary is disabled.

### ISSUE THREAD

**Issue by rsmarples** [getgrav/grav-plugin-feed#15]
Or so it seems.

See the blog page here - summary disabled.
https://roy.marples.name/blog

See the feed page here - summary enabled? How?
https://roy.marples.name/blog.atom

**Comment by lape** [comment]
It seems the RSS and Atom templates always use the blog post summary as source (before truncating). Maybe this should be changed to whole post content?

**Comment by flaviocopes** [comment]
PR merged, so closing
