### ISSUE TITLE
Absolute URLs Break Feed Links

### ISSUE THREAD

**Issue by chryton** [getgrav/grav-plugin-feed#20]
I recently switched to absolute URLs in my Grav install and found that the RSS feed links generated are broken. They return `http://home_url.com.rss` rather than `http://home_url.com/collection_name.rss`.

**Comment by flaviocopes** [comment]
This might depend on your theme, as those URLs are generated in it. Which theme is that?

This is how Antimatter does, and I tested it works fine: https://github.com/getgrav/grav-theme-antimatter/blob/develop/templates/partials/sidebar.html.twig#L1

**Comment by chryton** [comment]
I am using a child theme of Antimatter that I have lightly customized. I had to hardcode the urls to get it all to work correctly: http://thatonegameshow.rocks/

**Comment by flaviocopes** [comment]
Not able to replicate, if you can/want, post me your user/ folder (remove sensitive data) via Slack

**Comment by chryton** [comment]
DM'd on slack.
