### ISSUE TITLE
Use json_encode for JSON feed

### ISSUE THREAD

**Issue by cweiske** [getgrav/grav-plugin-feed#24]
JSONfeed shall be "difficult to do wrong." (see https://jsonfeed.org/version/1).

Unfortunately, the plugin does *not* use `json_encode` which would take care of all escaping, but creates the JSON manually. This is why rss/atom feeds broke: People built XML manually.

You're repeating history here with #21. Please do it better this time.

**Comment by rhukster** [comment]
how about next time, instead of making a rude remark that belittles other contributions you simply submit a PR and contribute yourself?

**Comment by cweiske** [comment]
yeah right.

**Comment by cweiske** [comment]
oh look: #25
