### ISSUE TITLE
Feed redirecting to homepage

### ISSUE THREAD

**Issue by trst** [getgrav/grav-plugin-feed#26]
Since updating to 1.6.1 I've noticed my feeds have begun redirecting to the main collections html, rather than serving either the rss, atom, or json feeds. I've tested both on my nginx production server and an apache2 local instance.

I can supply more detail on both if you need.

**Comment by rhukster** [comment]
There was a check added to ensure feed extensions AND a page defined collection are required to render a feed.  Also JSON feeds need to be enabled manually per the docs.  You can see it working here:

https://demo.getgrav.org/blog-skeleton/

This is running latest feed plugin on a collection defined in the homepage. JSON feed not enabled here btw.

**Comment by trst** [comment]
Interesting. I'm running the plugin without the json feed enabled, but I dice. I'd think it was an nginx config issue but it's the same on apache2. Perhaps I have my collection defined in some strange way. I'll look through that skeleton's source and check against my own.

**Comment by trst** [comment]
I've tried rebooting and reconfiguring from scratch, slowly adding in files from the repository and still I'm getting a redirect to html/php rather than being served rss or atom. Any thoughts on where things could be going wrong?

**Comment by Chouchen** [comment]
I have the same issue. 

The difference is : when I modify my blog templates or/and its frontmatter, it displays the feed the first time. But if I reload this page (F5), I'm redirected to the HTML/PHP ; and that until, I make another change or empty the cache.

**Comment by flaviocopes** [comment]
This is not something unique to the json feed, but also a bug on rss/atom. Introduced in the last release. Fixing right now

**Comment by flaviocopes** [comment]
@Chouchen @trst can you test my PR here? Thanks! https://github.com/getgrav/grav-plugin-feed/pull/27

**Comment by trst** [comment]
Tried and receiving the same issue: redirects to homepage. Tested locally on apache2 and on my production nginx server. Both with flushed caches and caching disabled.

See what I mean here: https://trst.co/home.rss

**Comment by flaviocopes** [comment]
🤔  that's strange, I'm not able to replicate any more, with my PR

**Comment by Chouchen** [comment]
It works for me : https://shikiryu.com/devblog.atom

**Comment by trst** [comment]
I had a peek at yours @chouchen and I can verify your feed is working properly.

@flaviocopes My guess is that there's something peculiar about my setup that's causing my issue and I just so happen to have stumbled across this caching issue. I'll have to do more debugging.

**Comment by MaciejTarmas** [comment]
Same issue here. This is a fresh installation for playing around:

https://tarmas.net/tarmas.pl/

Atom or RSS links redirect to homepage.

**Comment by rhukster** [comment]
@MaciejTarmas can you confirm which version Of the feed plugin you have installed?

**Comment by MaciejTarmas** [comment]
Version 1.6.1

It's a base installation with no tweaking.

![screen shot 2017-06-03 at 19 02 40](https://cloud.githubusercontent.com/assets/3435387/26755532/436f4330-488f-11e7-91b4-d215c3070a5c.png)

**Comment by rhukster** [comment]
It's weird that the feed plugin doesn't have icon, seems like something might be up with the blueprint.

**Comment by MaciejTarmas** [comment]
These 2 don't have an icon when checking for available plugins:

![screen shot 2017-06-03 at 20 15 26](https://cloud.githubusercontent.com/assets/3435387/26756011/89480428-4899-11e7-909a-9342eefdaa14.png)

Something to do with their names **starting** with "Feed"? InstagramFeed and TwigFeeds both have icons.

Let me know if I could provide any more info. I don't have shell access to this server, mind you, so it's either screenshots or whatever I can download through FTP.

**Comment by flaviocopes** [comment]
@MaciejTarmas can you test the latest develop branch version https://github.com/getgrav/grav-plugin-feed/archive/develop.zip? If you confirm it works I'll release it today

**Comment by MaciejTarmas** [comment]
Looks like it's working now. Still no icon though.

**Comment by core77** [comment]
Works for me. 

With icon in the installed plugins list.

**Comment by Habmala** [comment]
I updated to 1.6.1 last night and have the same issue. Glad to see some quick work here :) I can confirm that the development branch worked for me as well (copied from the zip above).

**Comment by flaviocopes** [comment]
Thanks for testing everyone, I pushed a new release.
