### ISSUE TITLE
Podcast feed

### ISSUE THREAD

**Issue by jgonyea** [getgrav/grav-plugin-feed#28]
Is there a way this can plugin can be used to create valid podcast feeds, or am I looking at needing to build my own plugin?

Thanks in advance.

**Comment by flaviocopes** [comment]
Hi, this has been asked quite a few times. I'm going to make a PR to introduce such functionality into this plugin.

**Comment by flaviocopes** [comment]
I added a first step in this direction: https://github.com/getgrav/grav-plugin-feed/pull/29

Let me know if the instructions there are clear enough or you need more guidance.

I don't have a podcast myself, I just read the format somewhere so feedback welcome if there's something to change or improve.

**Comment by jgonyea** [comment]
@flaviocopes Would you be willing to look at what I've got so far at https://github.com/jgonyea/grav-plugin-podcast/tree/develop?

**Comment by jgonyea** [comment]
Closing ticket.  My plugin at https://github.com/jgonyea/grav-plugin-podcast addresses this issue.
