### ISSUE TITLE
Override feed twig

### ISSUE THREAD

**Issue by jgonyea** [getgrav/grav-plugin-feed#30]
What's the proper way of overriding a twig template used by a plugin?  If someone wanted to create their own rss.html.twig, where would they put it within their plugin and call it?

I see at https://learn.getgrav.org/admin-panel/extending for how to override an admin template, but I'm looking for how to override another plugin's template.

Thanks in advance.

**Comment by rhukster** [comment]
The best way is to create a copy of the appropriate feed twig file in your theme's `templates/` folder.  Once copied, you can edit it there and it should override the file provided by the plugin.

**Comment by jgonyea** [comment]
Thanks,
I kept putting it into myplugin/OTHERPLUGIN/templates to sort of match the admin-panel extending documentation.

For anyone else coming here:
I used https://learn.getgrav.org/forms/blueprints/example-page-blueprint#in-a-plugin and the template was overridden by my plugin's template.
