### ISSUE TITLE
Enabled but getting 404

### ISSUE THREAD

**Issue by techmagus** [getgrav/grav-plugin-feed#31]
Hi,

I have the plugin enabled and settings are good, but I am getting 404 when opening .atom and .rss.

Here are the links:
https://verses.space/blog
https://verses.space/blog.atom
https://verses.space/blog.rss

Did I miss some setup step?

Thank you.

**Comment by rhukster** [comment]
Pretty sure this is related to your Nginx configuration.  It's not passing the .rss or .atom requests to the index.php file.  Can you paste me your nginx config???

**Comment by trst** [comment]
Doh! You were right. More embarrassing I'd already solved it.

Make sure that your nginx config isn't slurping the RSS or ATOM feeds into cache:

```
# Cache static files
location ~* \.(ogg|ogv|svg|svgz|eot|otf|woff|mp4|ttf|css|rss|atom|js|jpg|jpeg|gif|png|ico|zip|tgz|gz|rar|bz2|doc|xls|exe|ppt|tar|mid|midi|wav|bmp|rtf|swf)$ {
  add_header "Access-Control-Allow-Origin" "*";
  access_log off;
  log_not_found off;
  expires max;
}
```

Change to:
```
# Cache static files
location ~* \.(ogg|ogv|svg|svgz|eot|otf|woff|mp4|ttf|css|js|jpg|jpeg|gif|png|ico|zip|tgz|gz|rar|bz2|doc|xls|exe|ppt|tar|mid|midi|wav|bmp|rtf|swf)$ {
  add_header "Access-Control-Allow-Origin" "*";
  access_log off;
  log_not_found off;
  expires max;
}
```

**Comment by rhukster** [comment]
documented in README.md
