### ISSUE TITLE
Possible conflict with Feeds containing Page Inject content

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-feed#42]
Hi @rhuk, I have a blog list with child pages that use Page Inject to display additional content. For some reason, when I try to get an Atom/RSS feed from this blog I get an error message like this:

`RuntimeException (404)
Template "pdf.atom.twig" is not defined.`

Notice that it seems to have combined the template name `pdf` with atom related twig. Same goes for RSS.

Here is a user folder which should show the issue, go to the blog page and tap Atom or RSS and hopefully the error will be displayed:
https://1drv.ms/u/s!Aoj9Cstt0NJ0koc6U7YbjVE1Xk7R6w

Please let me know if you need any more info etc.

Thanks very much!
Paul

**Comment by paulhibbitts** [comment]
Thanks for the newest release of this plugin @rhukster. If you want a real-time look at this issue re: page inject templates causing an error with Feeds here is a link to an affected RSS feed:
https://test.hibbittsdesign.org/grav-feeds-page-inject/home.rss

Source web site:
https://test.hibbittsdesign.org/grav-feeds-page-inject

**Comment by rhukster** [comment]
Thanks, helpful to have a test site to work with

**Comment by rhukster** [comment]
oh, can can you provide a zip or a github repo i can download to test with?

**Comment by paulhibbitts** [comment]
thanks @rhukster , here is the exact user folder of the live website demo:
https://www.hibbittsdesign.org/user-page-inject-feeds.zip

Please let me know if there is anything I can do to help out.

**Comment by rhukster** [comment]
Fixed in 1.3.1 of page-inject.. should show up in GPM soonish.

**Comment by paulhibbitts** [comment]
Thank you so much @rhukster , I can confirm this fix on multiple test sites. I can now remove almost a dozen of extra Twig templates thanks to your detective work🙂
