### ISSUE TITLE
Validation failure for Feed Count and Feed Length

### ISSUE THREAD

**Issue by shanehoban** [getgrav/grav-plugin-feed#45]
It looks like these are set to text and have a validate class or what have you.

I can see what you are trying to do here, but setting a min value on a text field is looking for a minimum of x characters, as opposed to a value of minimum x.

![image](https://user-images.githubusercontent.com/1383797/56150897-d210bc00-5fa7-11e9-9917-2114cbbe16fe.png)

**Comment by rhukster** [comment]
Fixed
