### ISSUE TITLE
The RSS output for the posts omits paragraph breaks

### ISSUE THREAD

**Issue by ichik** [getgrav/grav-plugin-feed#5]
It's all just one big blob of a text for every item.

**Comment by rhukster** [comment]
I've actually made some improvements to Grav which adds a `truncate_html` twig filter, combined with feed updates, this allows HTML in feeds for more pleasant experience.  Can see this in action on getgrav.org feeds now.

**Comment by ichik** [comment]
Is there an easy way to override plugin templates for feeds?

**Comment by rhukster** [comment]
Of course, simply copy the `templates/feed.atom.twig` (or `.rss.twig`) to your theme's `templates/` folder and edit.
