### ISSUE TITLE
Not found

### ISSUE THREAD

**Issue by giansi** [getgrav/grav-plugin-feed#6]
Though the Blog online demo works, downloading the Blog skeleton returns a 404 not found when clicking both Atom and Rss buttons. I suppose this is the right place to open the issue.

**Comment by flaviocopes** [comment]
Cannot replicate the issue, work fine for me. Tried on Apache

**Comment by giansi** [comment]
I use to work with php web sever: maybe that's the cause?

**Comment by rhukster** [comment]
Yup, that's it.  It doesn't support advanced routing features.

**Comment by giansi** [comment]
Just tried now with apache on localhost and it works.

**Comment by jbouzekri** [comment]
I have the same issue with the PHP built in webserver as @giansi. It would be great if you were able to make it work with it for development purpose.
