### ISSUE TITLE
1.8.2 breaks all feeds

### ISSUE THREAD

**Issue by TheSpad** [getgrav/grav-plugin-feed#61]
After upgrading to 1.8.2 all feeds fail to load and instead simply redirect back to the original page (i.e. my.site/blog.rss just loads the content from my.site/blog although the url is still my.site/blog.rss).

Rolling back to 1.8.1 fixes the issue. JSON feeds aren't enabled, but it doesn't seem to make a difference to the issue whether they are or not.

Can replicate on a completely clean grav+admin install, just to eliminate anything we might have customised or changed that could have broken things.

Grav v1.7.15 - Admin v1.10.15

**Comment by rhukster** [comment]
I will look at this ASAP.

**Comment by rhukster** [comment]
I can't actually reproduce this in any of my test sites. .rss and .xml are both rendering feed correctly.

**Comment by TheSpad** [comment]
Hmmm, is there anything useful I can provide or gather to help try and troubleshoot? If it were just broken generally I'd put it down to something weird I was doing but the fact that it specifically breaks with 1.8.2 and not earlier versions suggests that there's something odd going on.

**Comment by petira** [comment]
I have the same problem. I also have the latest version of Grav and Admin Panel. The problem is related to the update to Feed v1.8.2.

**Comment by rhukster** [comment]
I just downloaded a fresh skeleton-blog-site installation: https://getgrav.org/download/skeletons/blog-site/2.0.0

The one I had didn't have latest Feed or SimpleSearch updates, so i just updated those via `bin/gpm update`

After doing that the feeds still worked fine for .rss and .atom .. no .json enabled.

**Comment by TheSpad** [comment]
So if it helps my test site was setup with the barebones install from https://github.com/getgrav/grav/releases/download/1.7.15/grav-admin-v1.7.15.zip - if I get a chance in the morning I'll try and replicate with the skeleton install.

**Comment by TheSpad** [comment]
Recreated my test site with the deployment from https://getgrav.org/download/skeletons/blog-site/2.0.0 and I'm still seeing the same behaviour - works with the shipped 1.8.0, breaks when upgraded to 1.8.2. I've stood up a 2nd identical copy for comparison.

v1.8.2
https://grav-test.spad.uk
https://grav-test.spad.uk/blog.rss

v1.8.0
https://grav-test2.spad.uk
https://grav-test2.spad.uk/blog.rss

If it makes any difference this is using nginx but the config is pretty much stock + the grav sample conf.

**Comment by rhukster** [comment]
Thanks! This helps a lot.  All my testing was on sites that were in subdirectories so I never saw that // issue, even at root.   I’ll get a fix out today.

**Comment by rhukster** [comment]
I've pushed a fix (see above). can someone please test to make sure this works for you now?

**Comment by TheSpad** [comment]
Did a direct install and it's looking good, will do some more testing to see if I can break it.

**Comment by rhukster** [comment]
I'm pretty sure it's good, so going to release it.

**Comment by Tugzrida** [comment]
Works on my site after doing the update through the admin panel :)

**Comment by TheSpad** [comment]
All good, thanks for sorting it so quickly @rhukster
