### ISSUE TITLE
plugin chokes on <> characters in markdown code blocks

### ISSUE THREAD

**Issue by ohnonot** [getgrav/grav-plugin-feed#7]
there it is in the title.
here's the ui error: 

> Server Error
> Sorry, something went terribly wrong!
> 0 – An exception has been thrown during the rendering of a template (“DOMDocumentFragment::appendXML(): Entity: line 1: parser error : error parsing attribute name”) in “feed.rss.twig” at line 20.

and here's the log error: https://paste.debian.net/409294/
by elimination i discovered that 2 of my markdown files (blog posts) contained a string like this: `<slkdjalksjdasjdlkasjlasj>` **inside code blocks or inline code** – removing the < and > fixed the feed problem.
also see: https://getgrav.org/forum#!/general:feed-throws-error-after-un

**Comment by rhukster** [comment]
This should resolve: https://github.com/getgrav/grav-plugin-feed/pull/41
