### ISSUE TITLE
Invalid RSS feed generated

### ISSUE THREAD

**Issue by ToeiRei** [getgrav/grav-plugin-feed#71]
My grav installations feed starts out like that:

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html>
<html>
    <head>
        <title>
            Rei's World
        </title>
        <link>
    </head>
    <body>
        https://toei.stargazer.at/de Rei's World de Sun, 04 Sep 2022 14:03:22 +0200
        <title>
```

Not sure what I'm doing wrong, but that doesn't look like valid RSS to me or the validator.

I'm using the Quark theme on the blog skeleton

**Comment by rhukster** [comment]
I clicked in your fedd link and it looks correct to me: https://toei.stargazer.at/de/blog.rss

**Comment by rhukster** [comment]
Ok, something is wrong.  Its like you don't have the feed's twig templates in your path and its falling back to html. Can you confirm what version of the feed plugin you have installed?

**Comment by ToeiRei** [comment]
Feed says it's  v1.8.5

**Comment by rhukster** [comment]
can you provide a copy of your `user/config/system.yaml`

**Comment by ToeiRei** [comment]
Nothing special in here, but there you go:

```
force_ssl: true

home:
  alias: '/blog'

languages:
  http_accept_language: true
  session_store_active: true
  supported: # Supported languages:
    - en # English language
    - de # German language
  default_lang: de # Set default language to German
  include_default_lang: true # If true, use /en/path instead of /path for default English language.
  include_default_lang_file_extension: true # If true, use .en.md file extension instead of .md for default langauge.
  content_fallback:
    de: ['de'] # No fallback for German.
    en: ['en', 'de'] #  English falls back to German version of the page.

pages:
  theme: quark
  process:
    markdown: true
    twig: false

cache:
  enabled: true
  check:
    method: hash
  driver: auto
  prefix: 'g'

twig:
  cache: true
  debug: false
  auto_reload: true
  autoescape: true

assets:
  css_pipeline: false
  css_minify: true
  css_rewrite: true
  js_pipeline: false
  js_minify: true

debugger:
  enabled: false
  twig: true
  shutdown:
    close_connection: true

session:
  enabled: true       # NOTE: Disable sessions if you do not use user login and/or forms.
  secure: true        # Use this as your site should be using HTTPS only
  httponly: true      # Protects session cookies against client side scripts and XSS
  samesite: Strict    # Prevent all cross-site scripting attacks
  split: true         # Separate admin session from the site session for added security

strict_mode:          # Test your site before changing these. Removes backward compatibility and improves site security.
  yaml_compat: false
  twig_compat: false
  blueprint_compat: false
```

**Comment by rhukster** [comment]
I'm unable to recreate your issue, i have setup a local quark-based grav skeleton that looks very similar to yours. Even setup the multilang the same as yours and the feeds work fine.  What other plugins do you have installed?

**Comment by ToeiRei** [comment]
Admin Panel -  v1.10.36
Archives -  v2.0.2
Aura - v2.1.2
Breadcrumbs - v1.6.2
Draft Preview - v0.1.0
Email - v3.2.0
Error - v1.8.0
External Links - v1.6.3
Feed -  v1.8.5
Flex Objects - v1.3.1
Form - v7.0.1
LangSwitcher - v3.0.1
Login - v3.7.1
Matomo - v1.2.1
Pagination - v1.4.3
Problems -  v2.1.1
Random -  v1.5.0
Related Pages -  v1.2.3
Shortcode Core -  v5.1.3
SimpleSearch - v2.3.0
Sitemap - v3.0.2
Static Social Embeds - v1.1.6
Taxonomy List -  v1.3.5
Tidyhtml -v1.0.3
YouTube -  v4.1.0

**Comment by ToeiRei** [comment]
TidyHTML is the one I guess that's messing up the rss page.

**Comment by rhukster** [comment]
My hunch is one of those plugins is causing the problem.  I would suggest disabling them one by one.  I test regularly with all the "official" Grav Team plugins so focus on the others..

**Comment by rhukster** [comment]
General rule of thumb is to have as few plugins as possible.  They can lead to conflicts, performance problems, or security issues. If possible use our "Team Grav" plugins, as we use and test these regularly. We don't test 3rd party ones.

**Comment by ToeiRei** [comment]
Yep, it was TidyHTML - I used it to adapt the template to get more readable output from the jumble to speed up debugging the html crap
