### ISSUE TITLE
RSS and Atom Feeds on the Feeds Demo Site Are Broken

### ISSUE THREAD

**Issue by thekenshow** [getgrav/grav-plugin-feed#75]
The RSS and ATOM feeds on [the Feeds demo site](https://getgrav.org/downloads/plugins) do not work. Screenshots below.

![image](https://github.com/getgrav/grav-plugin-feed/assets/998832/ab16ece8-eb4b-4f49-809d-058079b34dab)

![image](https://github.com/getgrav/grav-plugin-feed/assets/998832/36baba59-c0fc-4559-a096-440454019b26)

**Comment by rhukster** [comment]
ah yes, should be: https://demo.getgrav.org/blog-skeleton/blog.rss and https://demo.getgrav.org/blog-skeleton/blog.atom
