### ISSUE TITLE
Feeds : url to blog post does not contain FQDN and refers to localhost (reverse proxy setup)

### ISSUE THREAD

**Issue by nsteinmetz** [getgrav/grav-plugin-feed#8]
Hi,

I use grav in a docker container with a nginx on top of it as reverse proxy. I don"t have issues with the site but in the feeds, url of a blog post is ``http://localhost:9011/blog/mypost/`` instead of FQDN.

If I enable the ``reverse_proxy_setup``, I only have ``http//localhost/blog/mypost``.

Should I forward ``$http_host`` and things like that or is there a way to specify the public url of the site somewhere in grav ?

Can't find it so far.

Thanks,
Nicolas

**Comment by mrhein** [comment]
Hi,
this isn't releated to grav-plugin-feed...
but for you question ...
```

**Comment by nsteinmetz** [comment]
Ok, I could do it with adding this in nginx conf:

```
    location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_pass http://127.0.0.1:9001/;
    }
```

**Comment by nsteinmetz** [comment]
Oops, just saw your answer ; thanks !

As the bug occured only on the feed page, that's why I reported here. For all other url, it worked without doing anything.

Thanks !
